CREATE DATABASE IF NOT EXISTS aula17;
USE aula17;

CREATE TABLE Clientes (
	idCliente INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL,
    TipoCliente ENUM('PF','PJ') DEFAULT 'PF' NOT NULL
);

CREATE TABLE Usuarios(
	idUsuario INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL
);

ALTER TABLE usuarios
ADD COLUMN sexo VARCHAR(1);

ALTER TABLE usuarios
DROP COLUMN saldo;

ALTER TABLE usuarios
MODIFY COLUMN sexo BIT;

ALTER TABLE usuarios
CHANGE idUsuario id INT;