-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 22:07:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aula13
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aula13
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aula13` DEFAULT CHARACTER SET utf8 ;
USE `aula13` ;

-- -----------------------------------------------------
-- Table `aula13`.`tb_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula13`.`tb_departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aula13`.`tb_empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aula13`.`tb_empregado` (
  `id_empregado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_empregado`),
  INDEX `fk_tb_empregado_tb_departamento_idx` (`id_departamento` ASC) ,
  CONSTRAINT `fk_tb_empregado_tb_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `aula13`.`tb_departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
