CREATE DATABASE IF NOT EXISTS aula16;
USE aula16;

CREATE TABLE autores (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE livros (
	isbn VARCHAR(13) PRIMARY KEY NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    autor_id INT,
    FOREIGN KEY (autor_id) REFERENCES autores(id)
);

ALTER TABLE livros
ADD COLUMN genero VARCHAR(50);

ALTER TABLE livros
MODIFY COLUMN titulo VARCHAR(300);

ALTER TABLE livros
DROP COLUMN genero;